name: Reusable Build Workflow
 
on:
  workflow_call:
    inputs:
      var1:
        description: 'var1'
        required: true
        type: string
      var2:
        description: 'var2'
        required: false
        default: true
        type: boolean
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
        if: ${{ inputs.var2 == 'true' }}
      - name: test  
        run: echo "hello world ${{inputs.var1}}"
